apiVersion: apps/v1
kind: Deployment
metadata:
  name: contents-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contents
  template:
    metadata:
      labels:
        app: contents
    spec:
      containers:
        - name: contents
          image: kumarnitesh89/contents
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: storybooks
            - name: MONGO_URI
              value: "mongodb://contents-mongo-srv:27017/contents"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: contents-srv
spec:
  selector:
    app: contents
  type: ClusterIP
  ports:
    - name: contents
      protocol: TCP
      port: 3000
      targetPort: 3000
